MA-8642 Fix android 7.0 build error in frameworks/native
1. void cancelBuffer() change to status_t cancelBuffer() on android 7.0,
function need return value else can't pass build.
frameworks/native/services/surfaceflinger/DisplayHardware/VirtualDisplaySurface.cpp:532:1:
error: control may reach end of non-void function [-Werror,-Wreturn-type]

2. fix build error in computeCrop().
frameworks/native/services/surfaceflinger/LayerDim.cpp:94:19: error: no member named 'crop'
in 'android::Layer::Geometry'

Change-Id: I39708487237d30614fe9925e2c4cc0d6fbf39a84
Signed-off-by: Richard Liu <xuegang.liu@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/989
Reviewed-by: Xiaowen Liu <xiaowen.liu@nxp.com>